server:
  port: 63005

spring:
  application:
    name: bicyclestore-bicycle-service
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: info, health, shutdown
  endpoint:
    shutdown:
      enabled: true
